
import { makeDIToken } from "./utils";

export const PROPERTY_INJECT_METADATA_KEY = makeDIToken('PROPERTY_DEPENDENCY_INJECT_METADATA');
export const CONSTRUCTOR_INJECT_METADATA_KEY = makeDIToken('CONSTRUCTOR_DEPENDENCY_INJECT_METADATA');
export const ON_INIT_HOOK_METADATA_KEY = makeDIToken('ON_INIT_HOOK_METADATA');
