// ENVIRONMENT VARIABLES

/**
 * The key for the environment variable that specifies the name of the entry packages to be imported by the lambda.
*/
export const ENTRY_PACKAGES = 'ENTRY_PACKAGES';
export const DEBUG_PASSWORD = 'DEBUG_PASSWORD';
export const FILES_BUCKET_CUSTOM_DOMAIN_ENV_KEY = 'FILES_BUCKET_CUSTOM_DOMAIN';

export const RESPONSE_INCLUDE_METADATA = 'RESPONSE_INCLUDE_METADATA';
export const RESPONSE_ALWAYS_INCLUDE_METRICS = 'RESPONSE_ALWAYS_INCLUDE_METRICS';
export const RESPONSE_INCLUDE_METRICS_ON_DEBUG = 'RESPONSE_INCLUDE_METRICS_ON_DEBUG';
export const RESPONSE_PRETTY_PRINT_JSON = 'RESPONSE_PRETTY_PRINT_JSON';
