import { DetailsPageConfig } from "../../../ui-config-gen";

export const searchIndexSettingsDetailsConfig: DetailsPageConfig = {
  pageTitle: "Search Index Settings Details",
  pageType: "details",
  routePattern: "/system/search/indices/:entityName/settings-details",
  breadcrumbs: [
    { label: "Home", url: "/" },
    { label: "Search", url: "/system/search" },
    { label: "Indices", url: "/system/search/indices" },
    { label: "Index Details", url: "/system/search/indices/:entityName" },
    { label: "Settings Details" }
  ],
  pageHeaderActions: [
    { 
      label: "Edit Settings", 
      url: "/system/search/indices/:entityName/settings-edit", 
      type: "button" 
    },
    {
      label: "Apply Default Settings",
      openInModal: true,
      modalConfig: {
        modalType: "confirm",
        modalPageConfig: {
          title: "Apply Default Settings",
          content: "This will apply default settings automatically generated from your entity schema (searchable/filterable/sortable attributes). This will overwrite current settings."
        },
        apiConfig: {
          apiMethod: "POST",
          apiUrl: "/system/search/indices/:entityName/apply-default-settings"
        },
        responseConfig: {
          showModal: true,
          modalTitle: "Default Settings Applied"
        },
        submitSuccessRedirect: "/system/search/indices/:entityName/settings-details"
      }
    },
    {
      label: "Reset to Meilisearch Defaults",
      openInModal: true,
      modalConfig: {
        modalType: "confirm",
        modalPageConfig: {
          title: "Reset to Meilisearch Defaults",
          content: "This will reset all index settings to Meilisearch's default values (searchableAttributes: ['*'], filterableAttributes: [], etc.). This action cannot be undone."
        },
        apiConfig: {
          apiMethod: "POST",
          apiUrl: "/system/search/indices/:entityName/reset-settings"
        },
        submitSuccessRedirect: "/system/search/indices/:entityName/settings-details"
      }
    },
  ],
  detailsPageConfig: {
    detailApiConfig: { 
      apiMethod: "GET", 
      apiUrl: "/system/search/indices/:entityName/settings" 
    },
    columnsConfig: {
      columns: [
        { sortOrder: 1, fields: ['recommendation', 'hasDifferences'] },
        { sortOrder: 2, fields: ['settings'] },
        { sortOrder: 3, fields: ['autoGeneratedSettings'] },
        { sortOrder: 4, fields: ['diff'] }
      ]
    },
    propertiesConfig: [
      {
        name: "recommendation",
        label: "📊 Configuration Status",
        id: "recommendation",
        column: "recommendation",
        fieldType: "text"
      },
      {
        name: "hasDifferences",
        label: "Has Differences",
        id: "hasDifferences",
        column: "hasDifferences",
        fieldType: "boolean"
      },
      { 
        name: "settings", 
        label: "Current Settings", 
        id: "settings", 
        column: "settings", 
        fieldType: "json",
        helpText: "Settings currently active in the search engine"
      },
      { 
        name: "autoGeneratedSettings", 
        label: "Auto-Generated Settings (from Entity Schema)", 
        id: "autoGeneratedSettings", 
        column: "autoGeneratedSettings", 
        fieldType: "json",
        helpText: "Settings automatically generated based on your entity schema attributes"
      },
      { 
        name: "diff", 
        label: "Detailed Comparison", 
        id: "diff", 
        column: "diff", 
        fieldType: "json",
        helpText: "Field-by-field comparison showing added, removed, and unchanged values"
      }
    ]
  }
}; 