/**
 * @fileoverview Custom Page Configuration Types for FW24 Framework
 * 
 * This module defines the page configuration structures that are generated by the backend
 * and consumed by the frontend for dynamic page rendering. These configurations enable
 * the framework to render complete pages (list, form, details, dashboard, etc.) from
 * JSON without requiring frontend code changes.
 * 
 * ## Architecture Overview
 * 
 * The backend generates page configurations from entity schemas, which are then sent
 * to the frontend as JSON. The frontend uses these configurations to dynamically render
 * UI components using Ant Design and custom form/table components.
 * 
 * ## Page Types
 * 
 * - **list**: Table-based list pages with filters, sorting, pagination, and actions
 * - **form**: Create/edit forms with field validation and multi-column layouts
 * - **details**: Read-only detail views with multi-column layouts
 * - **dashboard**: Dashboard pages with widgets and metrics
 * - **accordion**: Accordion-based pages with nested sections
 * - **menu**: Navigation menu pages
 * 
 * ## Key Features
 * 
 * - Type-safe property configurations with full TypeScript support
 * - Template support for dynamic text rendering
 * - Relation field rendering with auto-generated configurations
 * - Visibility conditions for conditional UI rendering
 * - Multi-column layouts with flexible column configurations
 * - API integration with request/response handling
 * 
 * @see {@link fw24/src/entity/base-entity.ts} for entity schema definitions
 * @see {@link ui24/src/pages/PostAuth/PostAuthPage.tsx} for page rendering
 */

import type { FieldOptions, IConfirmModal, IEntityConfigReference, IEntityPageActionDrawerConfig, IFilterSegment, IModalApiConfig, INavigateToConfig, IRelationFieldConfig, IResponseDisplayConfig, ISectionsConfig, ITableExpandableConfig, ModalType, Template, VisibilityConfig } from "../../entity";
import { IEntityPageColumnConfig } from "../../entity/base-entity";

/**
 * Supported page types for dynamic page rendering.
 * Each page type maps to a specific frontend component and rendering strategy.
 * 
 * @example
 * ```ts
 * const listPage: PageType = 'list';  // Renders table-based list page
 * const formPage: PageType = 'form';  // Renders create/edit form
 * ```
 */
export type PageType = "list" | "form" | "details" | "custom" | "dashboard" | "accordion" | "menu";

/**
 * Field rendering types for UI components.
 * These types correspond to specific form field components in the frontend.
 * 
 * **Important**: Should NOT include structural types like "list" or "object".
 * Use `ConfigPropertyType` for structural types instead.
 * 
 * **Field Type Categories:**
 * 
 * **Basic Text Input:**
 * - text, textarea, password, email, hidden
 * 
 * **Numeric Input:**
 * - number, currency, percentage, range, slider, rating
 * 
 * **Date & Time:**
 * - date, time, datetime, duration, ttl
 * 
 * **Boolean & Toggle:**
 * - boolean, switch, toggle, checkbox
 * 
 * **Selection & Options:**
 * - select, multi-select, autocomplete, radio
 * 
 * **Visual & Display:**
 * - badge, tag, tags, progress, avatar, color, image, video, audio, qrcode
 * 
 * **Structured Data:**
 * - json, code, markdown, rich-text, wysiwyg
 * 
 * **Links & URLs:**
 * - url, phone, link
 * 
 * **Files & Media:**
 * - file, image, video, audio
 * 
 * **Special:**
 * - custom, icon
 * 
 * @see {@link ConfigPropertyType} for structural types
 */
export type ConfigFieldType =
    // Basic text input
    | "text"
    | "textarea"
    | "password"
    | "email"
    | "url"
    | "phone"
    | "hidden"

    // Numeric input
    | "number"
    | "currency"
    | "percentage"
    | "range"
    | "slider"
    | "rating"

    // Date & time
    | "date"
    | "time"
    | "datetime"
    | "duration"
    | "ttl"

    // Boolean & toggle
    | "boolean"
    | "switch"
    | "toggle"
    | "checkbox"

    // Selection & options
    | "select"
    | "multi-select"
    | "autocomplete"
    | "radio"

    // Visual & display
    | "badge"
    | "tag"
    | "tags"
    | "progress"
    | "avatar"
    | "color"
    | "icon"

    // Structured data
    | "json"
    | "code"
    | "markdown"
    | "rich-text"
    | "wysiwyg"

    // Links & navigation
    | "link"

    // Files & media
    | "file"
    | "image"
    | "video"
    | "audio"
    | "qrcode"

    // Timeline & events
    | "timeline"

    // Special
    | "custom";

/**
 * Data structure types for nested/complex properties.
 * These types represent the shape of data, not how it's rendered.
 * 
 * @see {@link ConfigFieldType} for UI rendering types
 */
export type ConfigPropertyType = "list" | "map" | "object";

/**
 * Property configuration for form fields, detail fields, and table columns.
 * This is the core configuration structure that defines how a field is rendered
 * and behaves in the UI.
 * 
 * Generated by the backend from entity schema attributes and sent to frontend as JSON.
 * 
 * @example
 * ```ts
 * // Simple text field
 * const nameField: PropertyConfig = {
 *   name: 'teamName',
 *   label: 'Team Name',
 *   column: 'teamName',
 *   fieldType: 'text',
 *   required: true,
 *   placeholder: 'Enter team name'
 * }
 * 
 * // Select field with API-loaded options
 * const leagueField: PropertyConfig = {
 *   name: 'leagueId',
 *   label: 'League',
 *   column: 'leagueId',
 *   fieldType: 'select',
 *   required: true,
 *   options: {
 *     apiMethod: 'GET',
 *     apiUrl: '/api/league',
 *     responseKey: 'data',
 *     optionMapping: { label: 'leagueName', value: 'leagueId' }
 *   }
 * }
 * 
 * // Relation field with auto-generated config
 * const teamField: PropertyConfig = {
 *   name: 'teamId',
 *   label: 'Team',
 *   column: 'teamId',
 *   fieldType: 'text',
 *   relationConfig: {
 *     routePattern: '/view-team/:teamId',
 *     modalConfigRef: { entityName: 'team', pageType: 'view' }
 *   }
 * }
 * ```
 */
export interface PropertyConfig {
    type?: ConfigPropertyType;
    id?: string;
    name: string;
    label: string;
    column: string;
    fieldType: ConfigFieldType;
    placeholder?: string;
    helpText?: string;
    hidden?: boolean;
    required?: boolean;
    validations?: string[];
    isVisible?: boolean;
    isEditable?: boolean;
    isListable?: boolean;
    isCreatable?: boolean;
    isFilterable?: boolean;
    isSearchable?: boolean;
    isIdentifier?: boolean;
    readOnly?: boolean;
    defaultValue?: any;
    options?: FieldOptions<any>;
    /**
     * Explicit renderer key (frontend ExtensionRegistry resolver key).
     * When present, UI uses this renderer before fieldType defaults.
     */
    renderer?: string;
    /**
     * Renderer-specific configuration blob.
     * Passed as-is to the renderer component.
     */
    rendererConfig?: Record<string, unknown>;
    /**
     * Runtime visibility configuration for role-based/conditional display.
     * Same as ITableColumnConfig.visibility for consistency.
     * 
     * Controls whether this field is visible/enabled based on:
     * - Actor roles/permissions
     * - Record state
     * - Context (pageType, modalDepth, etc.)
     * - Form values (for form fields)
     * 
     * @example
     * // Role-based
     * visibility: { requiredRoles: ['admin'] }
     * 
     * @example
     * // Conditional based on record
     * visibility: { record: { status: { eq: 'draft' } } }
     * 
     * @example
     * // Form field conditional
     * visibility: { formValues: { orderType: { eq: 'subscription' } } }
     */
    visibility?: VisibilityConfig;
    /**
     * Link configuration for navigable fields (e.g., clickable IDs)
     * Note: presence of linkConfig is sufficient - isLink is optional/deprecated
     */
    /** @deprecated Optional - presence of linkConfig is sufficient to indicate a link */
    isLink?: boolean;

    // =========================================================================
    // CODE EDITOR FIELD PROPERTIES (for fieldType: 'code', 'json', 'markdown')
    // =========================================================================
    /**
     * Code language for syntax highlighting (used when fieldType is 'code')
     * Supported: 'json', 'html', 'javascript', 'handlebars', 'text'
     */
    codeLanguage?: 'json' | 'html' | 'javascript' | 'handlebars' | 'text';
    /** Editor height in pixels (default: 300) */
    height?: number;
    /** Dark theme for code editor (default: false) */
    darkTheme?: boolean;
    /** Show line numbers in code editor (default: true) */
    lineNumbers?: boolean;
    /** Enable JSON validation for json language (default: true) */
    validateJson?: boolean;
    linkConfig?: {
        routePattern: string;
        /** Display text for the link - supports templates like "View {entityName}: {entityId}" */
        displayText?: Template;
    };
    /**
     * Relation field configuration for rendering related entities.
     * Auto-generated by backend from relation definitions.
     */
    relationConfig?: IRelationFieldConfig;
    /**
     * Modal configuration for fields that open in modal
     */
    openInModal?: boolean;
    // Support for list/map types from EntityAttribute
    items?: {
        type: ConfigFieldType;
        properties?: Array<PropertyConfig>;
    };
    properties?: Array<PropertyConfig>;

    // === Duration field configuration ===
    /**
     * Input unit of the stored duration value. Renderer converts to human-readable. Default: 'seconds'
     * @see DurationFieldMetadata in base-entity.ts
     */
    durationUnit?: 'ms' | 'seconds' | 'minutes' | 'hours' | 'days';
    /**
     * Display format for duration. Default: 'auto' (shows largest relevant units)
     * - 'auto': Automatically shows days/hours/minutes/seconds as needed
     * - 'long': Shows all units (e.g., "2d 3h 15m 30s")
     * - 'short': Shows only 2 most significant units (e.g., "2d 3h")
     * - 'compact': Shows single most significant unit (e.g., "2d")
     * @see DurationFieldMetadata in base-entity.ts
     */
    durationFormat?: 'auto' | 'long' | 'short' | 'compact';

    // === TTL field configuration ===
    /**
     * Input unit of the stored TTL value (Unix timestamp). Renderer shows remaining time. Default: 'seconds'
     * @see TTLFieldMetadata in base-entity.ts
     */
    ttlUnit?: 'ms' | 'seconds' | 'minutes' | 'hours';
    /**
     * Display format for TTL. Default: 'auto'
     * - 'auto': Automatically shows appropriate units based on remaining time
     * - 'long': Shows all units (e.g., "2d 3h 15m 30s remaining")
     * - 'short': Shows only 2 most significant units
     * - 'compact': Shows single most significant unit with suffix
     * @see TTLFieldMetadata in base-entity.ts
     */
    ttlFormat?: 'auto' | 'long' | 'short' | 'compact';
    /**
     * Auto-refresh TTL display every N seconds. Default: 0 (disabled)
     * Useful for countdown timers. Recommended: 1-60 seconds
     * @see TTLFieldMetadata in base-entity.ts
     */
    ttlAutoRefresh?: number;

    // === Timeline field configuration ===
    /**
     * Configuration for timeline field type.
     * Renders array data as a vertical timeline.
     * 
     * @example
     * ```ts
     * {
     *   name: 'checkpoints',
     *   label: 'Checkpoints',
     *   fieldType: 'timeline',
     *   timelineConfig: {
     *     mode: 'left',
     *     itemMapping: {
     *       labelField: 'name',
     *       timestampField: 'ts',
     *     }
     *   }
     * }
     * ```
     */
    timelineConfig?: {
        /** Layout mode: 'left' (default), 'right', or 'alternate' */
        mode?: 'left' | 'right' | 'alternate';
        /** Reverse the order of items */
        reverse?: boolean;
        /** Maximum number of items to show (default: all) */
        maxItems?: number;
        /**
         * Field mapping for extracting timeline item data from array elements.
         * If data is an array of objects, specify which fields to use.
         */
        itemMapping?: {
            /** Field for item label/title (default: 'name') */
            labelField?: string;
            /** Field for timestamp (default: 'ts' or 'timestamp') */
            timestampField?: string;
            /** Field for description (optional) */
            descriptionField?: string;
            /** Field for color/type (optional) - values: 'success', 'error', 'warning', 'info' */
            typeField?: string;
            /** Field for custom icon (optional) */
            iconField?: string;
        };
        /** Show timestamps (default: true) */
        showTimestamp?: boolean;
        /** Timestamp format (default: 'MMM D, h:mm:ss A') */
        timestampFormat?: string;
    };
}

/**
 * Property reference (short syntax or full config).
 * 
 * Supports two formats:
 * - **String shorthand:** `'fieldName'` - References field from entity schema, auto-inherits all metadata
 * - **Object syntax:** Full PropertyConfig for custom display settings
 * 
 * @example
 * // String shorthand (recommended for same-entity fields)
 * propertiesConfig: ['orderDate', 'status', 'total']
 * 
 * @example
 * // Mixed usage
 * propertiesConfig: [
 *   'orderDate',  // Uses schema metadata
 *   { name: 'status', label: 'Order Status', fieldType: 'badge' },  // Custom display
 *   'total'  // Uses schema metadata
 * ]
 */
export type PropertyReference = string | PropertyConfig;

/**
 * Array of property configurations.
 * Determines field order and display properties in forms and details pages.
 */
export type PropertiesConfig = ReadonlyArray<PropertyReference> | Array<PropertyReference>;

/**
 * Dashboard widget configuration for dashboard pages.
 * Defines the structure and behavior of individual dashboard widgets.
 * 
 * Supports various widget types including stats, charts, lists, actions, and descriptions.
 * Each widget can be configured with custom data sources, options, and time period selectors.
 * 
 * @example
 * ```ts
 * // Stat widget
 * const userCountWidget: DashboardWidgetConfig = {
 *   type: 'stat',
 *   title: 'Total Users',
 *   colSpan: 6,
 *   dataConfig: { apiUrl: '/api/stats/users', responseKey: 'count' }
 * }
 * 
 * // Chart widget with time period selector
 * const salesChartWidget: DashboardWidgetConfig = {
 *   type: 'chart',
 *   title: 'Sales Trend',
 *   colSpan: 12,
 *   showTimePeriodSelector: true,
 *   defaultTimePeriod: { period: 'last30days' },
 *   dataConfig: { apiUrl: '/api/stats/sales', responseKey: 'data' }
 * }
 * ```
 */
export interface DashboardWidgetConfig {
    type: 'stat' | 'chart' | 'list' | 'actions' | 'description' | 'markdown';
    title?: string;
    /** Optional description text for the widget (shown below title) */
    description?: string;
    colSpan?: number;
    maxWidth?: number | string;
    width?: number | string;
    dataConfig?: Record<string, unknown>;
    options?: Record<string, unknown>;
    showTimePeriodSelector?: boolean;
    defaultTimePeriod?: { period: string; range?: [ string, string ] };
    timezone?: string;
}

/**
 * Form page configuration structure for create/edit forms.
 * Generated by backend and consumed by frontend Form component.
 * 
 * Supports:
 * - Multi-column layouts
 * - Field validation
 * - API integration for create/update operations
 * - Success redirects and callbacks
 * - Custom form buttons
 * 
 * @example
 * ```ts
 * const createTeamForm: FormPageConfigStructure = {
 *   title: 'Create Team',
 *   apiConfig: {
 *     apiMethod: 'POST',
 *     apiUrl: '/api/team',
 *     responseKey: 'data'
 *   },
 *   propertiesConfig: [
 *     { name: 'teamName', label: 'Name', column: 'teamName', fieldType: 'text', required: true },
 *     { name: 'city', label: 'City', column: 'city', fieldType: 'text', required: true }
 *   ],
 *   formButtons: [
 *     { text: 'Save', url: '/submit' },
 *     { text: 'Cancel', url: '/list-team' }
 *   ],
 *   submitSuccessRedirect: '/list-team'
 * }
 * ```
 */
export interface FormPageConfigStructure {
    title?: string;
    helpText?: string;
    apiConfig: IModalApiConfig;
    detailApiConfig?: IModalApiConfig;
    formButtons: Array<string | {
        text: string;
        url: string;
    }>;
    propertiesConfig: PropertiesConfig;
    submitSuccessRedirect?: string;
    /**
     * Custom success message template.
     * @example successMessage: 'Record created successfully!'
     * @example successMessage: '{entityName} created successfully!'
     */
    successMessage?: Template;
    /**
     * Custom error message template.
     * @example errorMessage: 'Failed to create record'
     */
    errorMessage?: Template;
    columnsConfig?: IEntityPageColumnConfig;
}

/**
 * List page configuration structure for table-based list views.
 * Generated by backend and consumed by frontend Table component.
 * 
 * Supports:
 * - Pagination and sorting
 * - Column filters with operators
 * - Expandable rows for nested data
 * - Filter segments (quick filter tabs)
 * - Column grouping
 * - Relation field rendering
 * - Row actions and bulk actions
 * 
 * @example
 * ```ts
 * const teamListPage: ListPageConfigStructure = {
 *   title: 'Teams',
 *   apiConfig: {
 *     apiMethod: 'GET',
 *     apiUrl: '/api/team',
 *     responseKey: 'data',
 *     useSearch: true
 *   },
 *   propertiesConfig: [
 *     { 
 *       name: 'Team Name', 
 *       dataIndex: 'teamName', 
 *       fieldType: 'text', 
 *       isFilterable: true,
 *       isSortable: true 
 *     },
 *     { 
 *       name: 'City', 
 *       dataIndex: 'city', 
 *       fieldType: 'text',
 *       filterConfig: { filterType: 'text', defaultOperator: 'contains' }
 *     }
 *   ],
 *   segments: [
 *     { id: 'all', label: 'All Teams', filters: {}, default: true },
 *     { id: 'active', label: 'Active', filters: { status: { eq: 'active' } } }
 *   ]
 * }
 * ```
 */
export interface ListPageConfigStructure {
    title?: string;
    helpText?: string;
    apiConfig: {
        apiMethod: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';
        useSearch?: boolean;
        responseKey?: string;
        apiUrl: string;
    };
    propertiesConfig: ReadonlyArray<{
        type?: ConfigPropertyType;
        id?: string;
        name: string;
        dataIndex: string;
        fieldType: ConfigFieldType;
        placeholder?: string;
        helpText?: string;
        hidden?: boolean;
        required?: boolean;
        validations?: string[];
        isVisible?: boolean;
        isEditable?: boolean;
        isListable?: boolean;
        isCreatable?: boolean;
        isFilterable?: boolean;
        isSearchable?: boolean;
        isSortable?: boolean;
        isIdentifier?: boolean;
        readOnly?: boolean;
        defaultValue?: any;
        /**
         * Template for rendering column values.
         * Overrides default rendering when provided.
         * @example template: '{firstName} {lastName}'
         * @example template: { composite: ['firstName', 'lastName'], template: '{firstName} {lastName}' }
         */
        template?: Template;
        /**
         * Group title for column grouping.
         * Columns with same groupTitle will be grouped under a common header.
         * @example groupTitle: 'Player Info'
         */
        groupTitle?: string;
        /**
         * Relation field configuration for rendering related entities.
         * Auto-generated by backend from relation definitions.
         */
        relationConfig?: IRelationFieldConfig;
        // Filter configuration options
        filterConfig?: {
            defaultOperator?: string; // Default filter operator (e.g., 'contains', 'eq', 'in')
            availableOperators?: string[]; // Restrict available operators for this column
            predefinedOptions?: Array<{ label: string; value: string }>; // For dropdown/select filters
            filterType?: 'text' | 'select' | 'datetime' | 'number' | 'boolean'; // Filter input type
        };
        actions?: Array<{
            label?: string;
            /**
             * Dynamic action label template.
             * @example template: 'Edit {name}'
             */
            template?: Template;
            icon?: string;
            url?: string;
            type?: 'button' | 'link' | 'modal';
            openInModal?: boolean;
            modalConfig?: {
                modalType: ModalType;
                modalPageConfig: IConfirmModal | FormPageConfigStructure | ListPageConfigStructure | DetailsPageConfigStructure;
                apiConfig?: IModalApiConfig;
                submitSuccessRedirect?: string;
                successMessage?: Template;
                errorMessage?: Template;
            };
        }>;

        // for internal links
        /** @deprecated Optional - presence of linkConfig is sufficient to indicate a link */
        isLink?: boolean;
        linkConfig?: {
            routePattern: string;
            /** Display text for the link - supports templates like "View {entityName}: {entityId}" */
            displayText?: Template;
        };
    }>;
    /**
     * Expandable row configuration.
     * Allows displaying nested data (e.g., to-many relations) within table rows.
     */
    expandableConfig?: ITableExpandableConfig;

    /**
     * Filter segments (quick filter tabs) for the table.
     * Provides quick access to common filter sets.
     * 
     * @example
     * segments: [
     *   { id: 'all', label: 'All', filters: {}, default: true },
     *   { id: 'active', label: 'Active', filters: { isActive: { eq: true } } },
     *   { id: 'hot', label: 'Trending', filters: {...}, badge: 'HOT', badgeStatus: 'error' }
     * ]
     */
    segments?: Array<IFilterSegment>;
}

/**
 * Details page configuration structure for read-only detail views.
 * Generated by backend and consumed by frontend Details component.
 * 
 * Supports:
 * - Multi-column layouts (up to 3 columns)
 * - Rich field types (text, images, JSON, rich text, etc.)
 * - Relation field rendering with links and modals
 * - Nested object/array rendering
 * - Custom field formatting
 * 
 * @example
 * ```ts
 * const teamDetailsPage: DetailsPageConfigStructure = {
 *   title: 'Team Details',
 *   detailApiConfig: {
 *     apiMethod: 'GET',
 *     apiUrl: '/api/team/:teamId',
 *     responseKey: 'data'
 *   },
 *   propertiesConfig: [
 *     { name: 'teamName', label: 'Name', column: 'teamName', fieldType: 'text' },
 *     { name: 'city', label: 'City', column: 'city', fieldType: 'text' },
 *     { name: 'logo', label: 'Logo', column: 'logo', fieldType: 'image' }
 *   ],
 *   columnsConfig: {
 *     numColumns: 2,
 *     columns: [
 *       { sortOrder: 0, fields: ['teamName', 'city'] },
 *       { sortOrder: 1, fields: ['logo'] }
 *     ]
 *   }
 * }
 * ```
 */
export interface DetailsPageConfigStructure {
    title?: string;
    helpText?: string;
    detailApiConfig: IModalApiConfig;
    columnsConfig?: IEntityPageColumnConfig;
    propertiesConfig: PropertiesConfig;
    sectionsConfig?: ISectionsConfig;
}

/**
 * Wizard step configuration for multi-step forms.
 * Each step can have its own form fields and validation.
 * 
 * @example
 * ```ts
 * const step: WizardStepConfig = {
 *   title: 'Select Template',
 *   description: 'Choose a template to start with',
 *   fields: [
 *     { name: 'templateId', label: 'Template', fieldType: 'select', ... }
 *   ]
 * }
 * ```
 */
export interface WizardStepConfig {
    /** Step title */
    title: string;
    /** Step description (optional) */
    description?: string;
    /** Step icon (optional) */
    icon?: string;
    /** Form fields for this step */
    fields?: PropertiesConfig;
    /** API to call to get dynamic fields for this step */
    apiConfig?: {
        apiUrl: string;
        apiMethod: 'GET' | 'POST';
        body?: Record<string, unknown>;
        responseKey?: string;
    };
}

/**
 * Wizard page configuration for multi-step forms.
 * Provides a stepped form interface using Ant Design's Steps component.
 * Each step can have its own form fields and validation.
 * 
 * @example
 * ```ts
 * const wizardConfig: WizardPageConfigStructure = {
 *   title: 'Create from Template',
 *   steps: [
 *     { title: 'Select Template', fields: [...] },
 *     { title: 'Fill Variables', fields: [...] },
 *     { title: 'Preview', fields: [...] }
 *   ],
 *   apiConfig: {
 *     apiMethod: 'POST',
 *     apiUrl: '/api/create-from-template',
 *     responseKey: ''
 *   },
 *   showStepNumbers: true,
 *   allowStepClick: false
 * }
 * ```
 */
export interface WizardPageConfigStructure {
    /** Wizard title */
    title?: string;
    /** Help text shown at the top */
    helpText?: string;
    /** Wizard steps */
    steps: WizardStepConfig[];
    /** API configuration for final submission */
    apiConfig: IModalApiConfig;
    /** Initial form values */
    initialValues?: Record<string, unknown>;
    /** Show step numbers (default: true) */
    showStepNumbers?: boolean;
    /** Allow navigation by clicking steps (default: false) */
    allowStepClick?: boolean;
    /** Custom submit button text (default: 'Complete') */
    submitText?: string;
    /** Custom cancel button text (default: 'Cancel') */
    cancelText?: string;
    /** Show cancel button (default: true) */
    showCancel?: boolean;
    /** Success message after completion */
    successMessage?: string;
    /** Show success result after completion (default: false) */
    showSuccessResult?: boolean;
}

/**
 * Custom page configuration for ExtensionRegistry-registered components.
 * Used with modalType: 'custom' to render registered custom components in modals.
 * 
 * The componentKey references a component registered via:
 * ExtensionRegistry.register({ key: 'MyComponent', component: MyComponent, category: 'page' })
 * 
 * @example
 * ```ts
 * const customModalConfig: CustomPageConfigStructure = {
 *   componentKey: 'PostDistributionModal',
 *   componentProps: {
 *     previewUrl: '/api/preview',
 *     submitUrl: '/api/submit'
 *   }
 * }
 * ```
 */
export interface CustomPageConfigStructure {
  /** Component key registered in ExtensionRegistry */
  componentKey: string;
  /** Props to pass to the custom component */
  componentProps?: Record<string, unknown>;
  /** Optional title for the modal/page */
  title?: string;
  /** Optional help text */
  helpText?: string;
}

/**
 * Union type for modal page configurations.
 * Represents all possible page types that can be displayed in a modal.
 * 
 * Used when opening pages in modals (e.g., create form in modal, detail view in modal).
 */
export type ModalPageConfig = IConfirmModal | FormPageConfigStructure | ListPageConfigStructure | DetailsPageConfigStructure | WizardPageConfigStructure | CustomPageConfigStructure;

/**
 * Page action configuration for buttons and dropdowns in page headers.
 * Supports both navigation actions and modal-based actions with visibility conditions.
 * 
 * Actions can be:
 * - Simple navigation buttons (using `url`)
 * - Modal triggers (using `openInModal` + `modalConfig`)
 * - Dropdown menus with sub-items
 * 
 * @example
 * ```ts
 * // Simple navigation button
 * const editAction: IPageAction = {
 *   label: 'Edit',
 *   icon: 'edit',
 *   url: '/edit-team/:teamId'
 * }
 * 
 * // Modal action with form
 * const createAction: IPageAction = {
 *   label: 'Create Team',
 *   icon: 'plus',
 *   openInModal: true,
 *   modalConfig: {
 *     modalType: 'form',
 *     modalPageConfig: {
 *       title: 'Create Team',
 *       apiConfig: { apiMethod: 'POST', apiUrl: '/api/team' },
 *       propertiesConfig: [...],
 *       formButtons: [...]
 *     }
 *   }
 * }
 * 
 * // Dropdown with sub-items
 * const exportAction: IPageAction = {
 *   label: 'Export',
 *   icon: 'download',
 *   type: 'dropdown',
 *   items: [
 *     { label: 'Export as CSV', url: '/api/team/export/csv' },
 *     { label: 'Export as JSON', url: '/api/team/export/json' }
 *   ]
 * }
 * ```
 */
export interface IPageAction {
    /**
     * Unique identifier for this action. Used for override matching in merge logic.
     * When defaults are generated, they use standard IDs like 'view', 'edit', 'delete'.
     * Custom actions with the same ID will override defaults.
     */
    id?: string;

    label: string;

    /**
     * Dynamic label template (evaluated from routeParams or record context).
     * If provided, overrides static `label` field.
     * Can be simple string or complex template object.
     */
    template?: Template;

    url?: string;
    icon?: string;
    type?: 'button' | 'dropdown';
    items?: Array<Omit<IPageAction, 'items'>>;  // Items cannot have sub-items

    /** Open action in modal instead of navigating */
    openInModal?: boolean;

    /** Modal configuration (inline config or resolved from url) */
    modalConfig?: {
        modalType: ModalType;
        modalPageConfig?: ModalPageConfig;

        /** EITHER: Make API call (existing pattern) */
        apiConfig?: IModalApiConfig;
        submitSuccessRedirect?: string;
        /**
         * Navigation options for submitSuccessRedirect (replace history, pass state, etc.)
         * Uses react-router-dom's NavigateOptions: { replace?: boolean; state?: unknown; }
         */
        submitSuccessRedirectOptions?: {
            replace?: boolean;
            state?: unknown;
        };

        /** OR: Navigate without API call (new pattern) */
        navigateTo?: INavigateToConfig | string;

        /** OPTIONAL: Display API response in modal (instead of just toast notification) */
        responseConfig?: IResponseDisplayConfig;

        /**
         * Dynamic Configuration Extraction for Chaining/Wizard Flows
         * If provided, OperationExecutor looks for next-step config in the API response.
         * Useful for backend-driven wizards where each step is determined by the previous response.
         * @example dynamicConfigKey: 'nextStep'
         * Backend returns: { success: true, data: {...}, nextStep: { modalType: 'form', ... } }
         */
        dynamicConfigKey?: string;

        /**
         * Control modal closing behavior on error
         * - true: Close modal immediately on error
         * - false (default): Keep modal open so user can fix and retry
         */
        closeModalOnError?: boolean;

        /**
         * Skip showing success toast notification
         * Useful when responseConfig.showModal is true (avoid duplicate notifications)
         */
        skipSuccessToast?: boolean;

        /**
         * Skip showing error toast notification
         * Useful when you want custom error handling via callbacks
         */
        skipErrorToast?: boolean;

        /**
         * Pre-populate form fields from context (route params + record data).
         * Values are evaluated when modal opens. Supports:
         * - Static values: `{ isActive: true, priority: 1 }`
         * - Template strings: `{ teamId: '{teamId}', sport: '{sport}' }`
         * - Nested paths: `{ teamName: '{team.name}' }`
         */
        initialValues?: Record<string, any>;

        /**
         * If true, parent component will be refreshed after successful operation.
         * Triggers onSuccessCallback with API response data.
         * @default false
         */
        refreshParentOnSuccess?: boolean;

        /**
         * Custom success message template.
         * @example successMessage: '{entityName} created successfully!'
         */
        successMessage?: Template;

        /**
         * Custom error message template.
         * @example errorMessage: 'Failed to create {entityName}'
         */
        errorMessage?: Template;
    };

    /** Custom modal width. Default: auto-detect from page type */
    modalWidth?: number | string;

    /** Override resolved page title when opened in modal */
    modalTitle?: string;

    /** Hide this action when rendered inside a modal. Default: false */
    hideInModal?: boolean;

    /** Only open in modal on specified screen size. Default: always */
    openInModalCondition?: 'sm' | 'md' | 'lg' | 'xl';

    // =========================================================================
    // DRAWER SUPPORT
    // =========================================================================

    /** Open action in drawer (slide-out panel) instead of navigating */
    openInDrawer?: boolean;

    /**
     * Drawer configuration (when openInDrawer is true).
     * Uses shared drawer config type from base-entity.
     * 
     * @see {@link IEntityPageActionDrawerConfig} for full type definition
     */
    drawerConfig?: IEntityPageActionDrawerConfig;

    /** Entity config reference for drawer route resolution */
    drawerConfigRef?: IEntityConfigReference;

    /**
     * Visibility configuration for this action.
     * Controls visibility and enablement based on actor roles, record state, context, and custom logic.
     * 
     * When undefined, action is visible and enabled by default.
     * 
     * @example
     * // Simple role check
     * visibility: {
     *   requiredRoles: ['admin']
     * }
     * 
     * @example
     * // Record-based condition
     * visibility: {
     *   record: {
     *     status: { eq: 'active' }
     *   }
     * }
     */
    visibility?: VisibilityConfig;
}

/**
 * Base page configuration that all page types extend.
 * Provides common properties for page title, breadcrumbs, route pattern, and header actions.
 * 
 * All specific page types (list, form, details, dashboard, etc.) extend this base configuration.
 * 
 * @example
 * ```ts
 * const basePage: BasePageConfig = {
 *   pageName: 'team-list',
 *   pageTitle: 'Teams',
 *   pageType: 'list',
 *   routePattern: '/list-team',
 *   breadcrumbs: [
 *     { label: 'Home', url: '/' },
 *     { label: 'Teams' }
 *   ],
 *   pageHeaderActions: [
 *     { label: 'Create Team', url: '/create-team', icon: 'plus' }
 *   ]
 * }
 * ```
 */
export interface BasePageConfig {
    pageName?: string;
    /**
     * Page title - can be static string or dynamic template.
     * @example pageTitle: 'Dashboard'
     * @example pageTitle: '{userName} Dashboard'
     * @example pageTitle: { composite: ['userName', 'role'], template: '{userName} ({role}) - Dashboard' }
     */
    pageTitle: string | Template;
    pageType: PageType;
    routePattern?: string;
    /**
     * Breadcrumbs with template support.
     * @example
     * breadcrumbs: [
     *   { label: 'Home', url: '/' },
     *   { label: '{entityName}' }
     * ]
     */
    breadcrumbs?: Array<{ label: string | Template; url?: string }>;
    pageHeaderActions?: Array<IPageAction>;
}

/**
 * Dashboard page configuration.
 * Extends BasePageConfig with dashboard-specific widget configurations.
 * 
 * Supports multiple widget types (stat, chart, list, actions) with flexible layouts
 * and time period selectors for time-series data.
 * 
 * @example
 * ```ts
 * const dashboardPage: DashboardPageConfig = {
 *   pageName: 'main-dashboard',
 *   pageTitle: 'Dashboard',
 *   pageType: 'dashboard',
 *   dashboardPageConfig: {
 *     showTimePeriodSelector: true,
 *     defaultTimePeriod: { period: 'last30days' },
 *     widgets: [
 *       {
 *         type: 'stat',
 *         title: 'Total Users',
 *         colSpan: 6,
 *         dataConfig: { apiUrl: '/api/stats/users' }
 *       },
 *       {
 *         type: 'chart',
 *         title: 'Revenue Trend',
 *         colSpan: 12,
 *         dataConfig: { apiUrl: '/api/stats/revenue' }
 *       }
 *     ]
 *   }
 * }
 * ```
 */
export interface DashboardPageConfig extends BasePageConfig {
    pageType: "dashboard";
    dashboardPageConfig: {
        showTimePeriodSelector?: boolean;
        defaultTimePeriod?: { period: string; range?: [ string, string ] };
        widgets: DashboardWidgetConfig[];
        timezone?: string;
    }
}

/**
 * Form page configuration.
 * Extends BasePageConfig with form-specific configurations for create/edit operations.
 * 
 * @example
 * ```ts
 * const createTeamPage: FormPageConfig = {
 *   pageName: 'create-team',
 *   pageTitle: 'Create Team',
 *   pageType: 'form',
 *   cardStyle: { width: '800px' },
 *   formPageConfig: {
 *     apiConfig: { apiMethod: 'POST', apiUrl: '/api/team' },
 *     propertiesConfig: [...],
 *     formButtons: [...]
 *   }
 * }
 * ```
 */
export interface FormPageConfig extends BasePageConfig {
    pageType: "form";
    cardStyle?: {
        width: string;
    };
    formPageConfig: FormPageConfigStructure;
}

/**
 * List page configuration.
 * Extends BasePageConfig with table-specific configurations for listing data.
 * 
 * @example
 * ```ts
 * const teamListPage: ListPageConfig = {
 *   pageName: 'list-team',
 *   pageTitle: 'Teams',
 *   pageType: 'list',
 *   listPageConfig: {
 *     apiConfig: { apiMethod: 'GET', apiUrl: '/api/team' },
 *     propertiesConfig: [...]
 *   }
 * }
 * ```
 */
export interface ListPageConfig extends BasePageConfig {
    pageType: "list";
    listPageConfig: ListPageConfigStructure;
}

/**
 * Details page configuration.
 * Extends BasePageConfig with detail view configurations for displaying record details.
 * 
 * @example
 * ```ts
 * const teamDetailsPage: DetailsPageConfig = {
 *   pageName: 'view-team',
 *   pageTitle: 'Team Details',
 *   pageType: 'details',
 *   detailsPageConfig: {
 *     detailApiConfig: { apiMethod: 'GET', apiUrl: '/api/team/:teamId' },
 *     propertiesConfig: [...]
 *   }
 * }
 * ```
 */
export interface DetailsPageConfig extends BasePageConfig {
    pageType: "details";
    detailsPageConfig: DetailsPageConfigStructure;
}

/**
 * Accordion page configuration.
 * Extends BasePageConfig with accordion-specific configurations for nested sections.
 * 
 * Each accordion section can contain any page type (list, form, details, dashboard).
 * 
 * @example
 * ```ts
 * const teamAccordionPage: AccordionPageConfig = {
 *   pageName: 'team-overview',
 *   pageTitle: 'Team Overview',
 *   pageType: 'accordion',
 *   accordionPageConfig: {
 *     accordions: {
 *       details: {
 *         pageTitle: 'Team Details',
 *         pageType: 'details',
 *         detailsPageConfig: {...}
 *       },
 *       players: {
 *         pageTitle: 'Players',
 *         pageType: 'list',
 *         listPageConfig: {...}
 *       }
 *     }
 *   }
 * }
 * ```
 */
export interface AccordionPageConfig extends BasePageConfig {
    pageType: "accordion";
    accordionPageConfig: {
        accordions: Record<string, {
            /**
             * Accordion section title - supports templates.
             * @example pageTitle: 'User Details'
             * @example pageTitle: '{userName} Information'
             */
            pageTitle: string | Template;
            pageType: "list" | "form" | "details" | "dashboard";
            listPageConfig?: ListPageConfigStructure;
            formPageConfig?: FormPageConfigStructure;
            detailsPageConfig?: DetailsPageConfigStructure;
            dashboardPageConfig?: DashboardPageConfig[ 'dashboardPageConfig' ];
        }>;
    };
}

/**
 * Menu page configuration.
 * Extends BasePageConfig with menu-specific configurations for navigation menus.
 * 
 * Supports nested menu items, grouping, and custom ordering.
 * 
 * @example
 * ```ts
 * const mainMenuPage: MenuPageConfig = {
 *   pageName: 'main-menu',
 *   pageTitle: 'Main Menu',
 *   pageType: 'menu',
 *   menuPageConfig: {
 *     menuItems: [
 *       {
 *         label: 'Teams',
 *         key: 'teams',
 *         icon: 'team',
 *         children: [
 *           { label: 'All Teams', key: 'all-teams', url: '/list-team' },
 *           { label: 'Create Team', key: 'create-team', url: '/create-team' }
 *         ]
 *       },
 *       {
 *         label: 'Settings',
 *         key: 'settings',
 *         url: '/settings',
 *         icon: 'setting'
 *       }
 *     ]
 *   }
 * }
 * ```
 */
export interface MenuPageConfig extends BasePageConfig {
    pageType: "menu";
    menuPageConfig: {
        menuItems: Array<{
            label: string;
            key: string;
            url?: string;
            icon?: string;
            children?: Array<{
                label: string;
                key: string;
                url?: string;
                icon?: string;
            }>;
            group?: string;
            order?: number;
        }>;
    };
}

/**
 * Union type for all custom page configuration options.
 * Used as the input type for makeCustomPageConfig function.
 */
export type CustomPageOptions = ListPageConfig | FormPageConfig | DetailsPageConfig | DashboardPageConfig | AccordionPageConfig | MenuPageConfig;

/**
 * Factory function for creating custom page configurations.
 * Takes a page-specific configuration and returns a normalized page config structure.
 * 
 * This function ensures consistent structure across all page types by applying
 * base config properties and page-specific config properties.
 * 
 * @param options - Page configuration options (list, form, details, dashboard, accordion, or menu)
 * @returns Normalized page configuration
 * 
 * @example
 * ```ts
 * const listPage = makeCustomPageConfig({
 *   pageName: 'team-list',
 *   pageTitle: 'Teams',
 *   pageType: 'list',
 *   listPageConfig: {
 *     apiConfig: { apiMethod: 'GET', apiUrl: '/api/team' },
 *     propertiesConfig: [...]
 *   }
 * });
 * ```
 */
export function makeCustomPageConfig(options: CustomPageOptions) {
    const baseConfig = {
        pageName: options.pageName,
        pageTitle: options.pageTitle,
        pageType: options.pageType,
        routePattern: options.routePattern,
        breadcrumbs: options.breadcrumbs || [],
        pageHeaderActions: options.pageHeaderActions || [],
    };

    switch (options.pageType) {
        case "list":
            return {
                ...baseConfig,
                listPageConfig: options.listPageConfig
            };
        case "form":
            return {
                ...baseConfig,
                cardStyle: options.cardStyle,
                formPageConfig: options.formPageConfig
            };
        case "details":
            return {
                ...baseConfig,
                detailsPageConfig: options.detailsPageConfig
            };
        case "dashboard":
            return {
                ...baseConfig,
                dashboardPageConfig: options.dashboardPageConfig
            };
        case "accordion":
            return {
                ...baseConfig,
                accordionsPageConfig: options.accordionPageConfig.accordions
            };
        case "menu":
            return {
                ...baseConfig,
                menuPageConfig: options.menuPageConfig
            };
        default:
            return baseConfig;
    }
}
